### ISSUE TITLE
How to deal with biological replicates - tradis_essentiality.R

### ISSUE THREAD

**Issue by subwaystation** [sanger-pathogens/Bio-Tradis#100]
Hi @lbarquist ,

I am wondering how to deal with biological replicates (e.g. 3) when calculating the essential genes using 
```
tradis_essentiality.R
```
Do you just take the median of the insertion sizes 3 replicates, calculate the insertion index once and then plug them into the script? 
Or is there a way to calculate an interval range?
Any other ideas?
Thanks!

Best,
Simon

**Comment by lbarquist** [comment]
Hi Simon,

This isn't something I've really done before, since most projects I've worked on have just had a single input library. 

I think the median approach you suggest should work? If you wanted to get really fancy, you could probably put errors/deviations on these medians (median absolute deviations across the replicates is one idea?) and use these in some kind of significance calculation. Whether or not this is overkill probably depends on how certain you need to be in your results downstream - from my experience looking at essential genes from TraDIS experiments in different bacteria, I suspect this might take a lot of work to get to more or less the same result in the end, though I'd be quite happy to be proved wrong.

Of course the easiest thing if you just want a quick result would just be to run the script three times on your three libraries, check that they agree, and maybe exclude things that are borderline or switch categories in different experiments.

Feel free to email me directly if you want any advice on specific data, or just a second set of eyes to sanity-check.

-Lars

**Comment by subwaystation** [comment]
Hi Lars,

if you have only worked with a single input library, I am wondering from where you got the statistical power for 
```
tradis_comparison.R
```
? I would expect edgeR to require at least 2 replicates of a group, right?
I am having 3 independent biological replicates per group.

Well, the median approach was the best one I could think of. 
So instead of taking the median I take the MAD, did I understand that right? And find a significance how?
If you could elaborate on that (or email me personally) I would be very happy.

I am not quite sure if running the thing 3 times in a row would be statistically correct. Of course we could perform as you suggest, but we would not able to take any technical or human bias into account? I would expect that each replicate might behave differently. 
Lets say I have 0 | 1 | 25 as insertion counts for one replicate and gene. The median would be 1, but the question is, would that be close to the biological truth? If your experience tells you that, then I would be happy to follow that way. However, how would I justify that in a paper? You think that would fly?

I have to ask, if I can forward you any data, then I will come back to you! Thanks for the offer.

Best,
Simon

**Comment by subwaystation** [comment]
Thanks!
Sure, I will come back to you.
